baseURL = "https://wuzzy.codeberg.page/Repixture/"
title = "Repixture Player Manual"
buildFuture = false
enableMissingTranslationPlaceholders = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

disableKinds = ["sitemap"]

copyright = "This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International license."
languageCode = "en"

[author]
name = "Wuzzy"
email = "Wuzzy@disroot.org"

[taxonomies]

[outputs]
home = ["HTML"]
page = ["HTML"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[privacy]
[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = true

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true


