minetest.register_alias("default:sign", "rp_signs:sign")

minetest.register_alias("rp_default:sign", "rp_signs:sign")
minetest.register_alias("rp_default:sign_birch", "rp_signs:sign_birch")
minetest.register_alias("rp_default:sign_oak", "rp_signs:sign_oak")
minetest.register_alias("rp_default:sign_r90", "rp_signs:sign_r90")
minetest.register_alias("rp_default:sign_oak_r90", "rp_signs:sign_oak_r90")
minetest.register_alias("rp_default:sign_birch_r90", "rp_signs:sign_oak_r90")

minetest.register_alias("rp_default:sign_painted", "rp_signs:sign_painted")
minetest.register_alias("rp_default:sign_birch_painted", "rp_signs:sign_birch_painted")
minetest.register_alias("rp_default:sign_oak_painted", "rp_signs:sign_oak_painted")
minetest.register_alias("rp_default:sign_r90_painted", "rp_signs:sign_r90_painted")
minetest.register_alias("rp_default:sign_oak_r90_painted", "rp_signs:sign_oak_r90_painted")
minetest.register_alias("rp_default:sign_birch_r90_painted", "rp_signs:sign_oak_r90_painted")
